source: .
title: Blazing Code!
description: I tutorial per sviluppare applicazioni web con ASP.NET Core...
google_analytics: 
show_downloads: true
theme: jekyll-theme-slate

gems:
  - jekyll-mentions
